/**
 * Seed script — creates dummy users for testing.
 * Run with:  node src/seed-users.js
 *
 * After seeding, all credentials are written to DEV_CREDENTIALS.md
 * at the project root so testers can easily find login details.
 */
const path = require('path');
const fs = require('fs');
const { sequelize } = require('./config/database');
const User = require('./models/User');

const ROLES = ['individual', 'contractor', 'company', 'dealer', 'operator', 'mechanic', 'admin', 'super_admin'];
const DEFAULT_PASSWORD = 'password123';

async function seedUsers() {
  try {
    await sequelize.authenticate();
    console.log('✅ Database connected');
    
    // Ensure tables exist
    await sequelize.sync();

    let createdCount = 0;
    const allUsers = []; // collect creds for the file

    for (const role of ROLES) {
      // Create 2-3 users per role
      const usersToCreate = Math.floor(Math.random() * 2) + 2; // 2 or 3
      
      for (let i = 1; i <= usersToCreate; i++) {
        const email = `dummy_${role}_${i}@yantrasetu.dev`;
        // Generate a deterministic-ish 10+digit Indian phone number
        const prefix = Math.random() > 0.5 ? '9' : '8';
        const phone = prefix + Math.floor(100000000 + Math.random() * 900000000).toString().substring(0, 9);
        
        // Check if user exists by email
        const existing = await User.findOne({ 
          where: { email } 
        });
        
        if (!existing) {
          const user = await User.create({
            phone: phone,
            password: DEFAULT_PASSWORD,
            firstName: 'Dummy',
            lastName: `${role.charAt(0).toUpperCase() + role.slice(1)} ${i}`,
            email: email,
            userType: role,
            accountTier: 'free',
            isVerified: true,
            isActive: true,
            isBanned: false,
            rating: 4.5,
            reviewCount: 10
          });
          createdCount++;
          allUsers.push({ phone, email, role, password: DEFAULT_PASSWORD, status: 'created' });
        } else {
          allUsers.push({ phone: existing.phone, email, role, password: DEFAULT_PASSWORD, status: 'existing' });
        }
      }
      console.log(`✅ Checked/Created users for role: ${role}`);
    }

    // --- Write DEV_CREDENTIALS.md ---
    const credsPath = path.resolve(__dirname, '../../DEV_CREDENTIALS.md');
    let md = `# YantraSetu — Development Credentials\n\n`;
    md += `> ⚠️ **For local development only. Do NOT use in production.**\n\n`;
    md += `> Auto-generated by \`node src/seed-users.js\` on ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}\n\n`;

    // Admin section
    md += `## Admin Account\n\n`;
    md += `| Phone | Password | Email | Role |\n`;
    md += `|-------|----------|-------|------|\n`;
    md += `| \`9000000001\` | \`admin@123\` | \`admin@yantrasetu.dev\` | admin |\n\n`;
    md += `Seed admin separately: \`node src/seed-admin.js\`\n\n`;

    // Dummy users table
    md += `## Test Users (all passwords: \`${DEFAULT_PASSWORD}\`)\n\n`;
    md += `| # | Role | Phone | Email |\n`;
    md += `|---|------|-------|-------|\n`;
    allUsers.forEach((u, idx) => {
      md += `| ${idx + 1} | ${u.role} | \`${u.phone}\` | \`${u.email}\` |\n`;
    });

    md += `\n### How to seed\n\n`;
    md += `\`\`\`bash\ncd backend\nnode src/seed-admin.js     # admin account\nnode src/seed-users.js     # all test users (this also regenerates this file)\nnode src/seed-listings.js  # machinery listings with images\n\`\`\`\n\n`;
    md += `> OTPs are logged to the backend console in dev mode.\n`;

    fs.writeFileSync(credsPath, md, 'utf-8');
    console.log(`\n📄 Credentials written to ${credsPath}`);

    console.log(`\n🎉 Seed completed! Created ${createdCount} new dummy users.`);
    console.log(`🔑 All dummy users share the password: ${DEFAULT_PASSWORD}`);
    console.log(`📧 Example logins: dummy_mechanic_1@yantrasetu.dev, dummy_operator_1@yantrasetu.dev, etc.\n`);

    await sequelize.close();
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seedUsers();

